### PR TITLE
Added java script utility class under utils package

### PR DESCRIPTION
**Pull request by sarangholey**
Please do review my code of javascript utility

### CODE REVIEW

**Review by akashdktyagi — CHANGES_REQUESTED** [review]
can u put this file directly under utils folder

**Comment by sarangholey** [comment]
Ok I will do it

**Comment by sarangholey** [comment]
Done with changes as mentioned

**Comment by sarangholey** [comment]
Added the excel data reader utility in utils package with the necessary dependencies in pom.xml, please review it.

**Review by akashdktyagi — APPROVED** [review]

**Comment by akashdktyagi** [comment]
@sarangholey merged this changes to master.

**Pull request merged**
